### ISSUE TITLE
Initial version roadmap

### ISSUE THREAD

**Issue by wkillerud** [wkillerud/dart-sass-language-server#2]
Below is a high-level breakdown of what's needed to make an initial version of the Sass language server.

For this initial version we will use the Node-based [Some Sass](https://github.com/wkillerud/some-sass/tree/main/packages/language-server) language server as a reference. We use [sass_api](https://pub.dev/packages/sass_api) as the foundation (replaces the scanner and parser). Unless otherwise noted we aim for feature parity with Some Sass.

The work is divided in two phases.

1. During phase one the features should be done in order.
2. Features in phase two can be worked on in parallell.

## Reference material

- [some-sass-language-server](https://github.com/wkillerud/some-sass) (what we're porting, see packages/language-service/src/)
- [sass_api](https://pub.dev/packages/sass_api) (replaces the scanner + parser in some-sass-language-server)
- [lsp_server](https://pub.dev/packages/lsp_server)
- [Language server protocol specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/)

## Preparations

- [ ] Set up dart analyze, including CI with [sass org configuration](https://github.com/sass/dart-sass/tree/main/analysis) (see [sass/migrator](https://github.com/sass/migrator/))
- [ ] Set up a data source for CSS for hover info, completions (likely [w3c/webref](https://github.com/w3c/webref) and [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data), see [vscode-custom-data](https://github.com/microsoft/vscode-custom-data?tab=readme-ov-file) for inspiration)
- [ ] Set up a data source for Sass for hover info, completions

## Phase one

Navigation features. Should be done in order.

- [ ] Document links
- [ ] Document symbols
- [ ] Workspace symbols
- [ ] Find definition
- [ ] Find references

## Phase two

Features that depend on navigation, and some independent features. Can be worked on in parallell.

- [ ] Completions aka IntelliSense
- [ ] Hover information
- [ ] Rename symbol
- [ ] Diagnostics
- [ ] Color decorators
- [ ] Signature help
- [ ] Document highlights
- [ ] Folding ranges
- [ ] Code actions

**Comment by MrBns** [comment]
Interesting !!
so will it have **@import intellisense** **@mixin** **@function** etc intellisense for across multiple files ?

**Comment by wkillerud** [comment]
Yes, among other things (#11).
